MGG-1555 [#ccc] svg_processing: Disable type-checking
We were getting following python error outside VSCode environment.
  Traceback (most recent call last):
    File "svg2cKPI.py", line 24, in <module>
      from svg_processing import BasicRect
    File "/GLIB_BUILD/VGLITE/gpu-vglite-toolkit/svg_processing.py", line 66, in <module>
      _CMD_PARAM_TABLE: dict[str, int] = {
  TypeError: 'type' object is not subscriptable

Cause it that dictionary object is not scriptable
This error was not solved by including Dict class from typing module.
So, we've disable time checking on constant dictionary.

Signed-off-by: Nilam Gaikwad <nilam.gaikwad@nxp.com>